### ISSUE TITLE
Error result

### ISSUE THREAD

**Issue by xyx233** [Rappsilber-Laboratory/xiSPEC_ms_parser#14]
Hello, every time I upload mzml and CSV on xispec,  always get 1 error and blank results

**Comment by lars-kolbowski** [comment]
Hi, could you please provide me with more info on the error and/or the files you are trying to upload?

**Comment by lars-kolbowski** [comment]
I see, yes the problem was most likely your mzML version (which was too new). I just deployed a fix that includes additional .obo files, so now this should work. Could you please try again?

**Comment by xyx233** [comment]
Thank you for your help,our problem has been solved.


谢雨欣
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rappsilber-Laboratory/xiSPEC_ms_parser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Rappsilber-Laboratory/xiSPEC_ms_parser] Error result (Issue #14)





 
I see, yes the problem was most likely your mzML version (which was too new). I just deployed a fix that includes additional .obo files, so now this should work. Could you please try again?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
