### ISSUE TITLE
Help with bulk upload of crosslinked spectra

### ISSUE THREAD

**Issue by TaraBartolec** [Rappsilber-Laboratory/xiSPEC_ms_parser#22]
Dear xiSPEC team,

I would like to upload my crosslinks (identified using the Mango-Comet-XLinkProphet TPP pipeline) for automated spectral annotation. I have made a test CSV file with a subset of the IDs from one file and tried to use the .ms2 formatted spectra generated from this pipeline (containing only spectra with putative crosslinks). 

Unfortunately, I got the following error message from the batch upload:

_log id: 7jb0v3b18m7r8moaib69pd9kr3_1646273879.log (include this in the github issue)
error type: Error
message: Unsupported peak list file type for: 04112020_Hpm1KO_RV_F10_XL_5uL_1.ms2
id: undefined_

I have checked a few examples in the manual entry section of xiSPEC by pasting peak lists from .mgf scan header plus matched ID details from CSV - it works as expected. I have also tried to generate a mzID (mzIdentML) of the entire dataset and upload it alongside the .ms2 files, though could not upload it due to the size.

Here is a OneDrive folder with all files:
https://unsw-my.sharepoint.com/:f:/g/personal/z5187327_ad_unsw_edu_au/Etw11p_2vHFDq5umLA3FfpgB8zMaOwjIkFCQlJteFhMn4A?e=IWNa4f

Would it be possible to get some help with the upload of my dataset?

Best,
Tara Bartolec

**Comment by colin-combe** [comment]
Hi Tara,

which website are you uploading the data to?

it may be that the version of the software in use at https://spectrumviewer.org doesn't support ms2 peaklists, but the version in use at https://xiview.org does.

You'll need to create an account first to use xiview.org.

The csv format for the xiview.org website is a bit different - it also needs the position of the peptide in the protein (as it will try to draw the crosslink network). The CSV formats for xiview are described here - https://xiview.org/xiNET_website/csvFormats.php

There is also a way to view only the annotated spectra in xiVIEW (and not a network, if thats what you want) but its a bit difficult to find, I can explain if need be.

You should also be able to upload 
- the mzIdentML file 
- all the ms2 peaklists zipped together into a single file
and that should work. 

However, I just tested that for you and it didn't work. The xiVIEW website complained saying "invalid xml syntax". The HUPO-PSI validator for mzIdentML just seems to crash when asked to validate it.

(The validator is at https://github.com/HUPO-PSI/mzIdentML/tree/master/validator, best to use whats in the zip file there if you want to run it.)

I think the mzIdentML file maybe has invalid characters in it - eg. on line 3031?

The best way forward is probably to fix the mzIdentML file (assuming I'm right that its broken).

Becasue it is crosslinking data you may be better using xiVIEW than xiSPEC. As i say, I'm not sure if ms2 files work in xiSPEC (@lars-kolbowski ?)

Anyway, happy to help, let us know how you get on,
best wishes,
Colin

**Comment by TaraBartolec** [comment]
Hi Colin,

Unfortunatley I couldn't quite figure out a way to get the spectral files to play nice in either xiSPEC or xiVIEW, but managed to find a way to produce annotated spectra in-house. Not sure what the problem was exactly, but thank you for your help nonetheless. 

Best,
Tara
